// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Configuration for Config Sync
public struct ConfigSync: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Git repo configuration for the cluster.
  public var git: GitConfig? = nil

  /// Specifies whether the Config Sync Repo is
  /// in "hierarchical" or "unstructured" mode.
  public var sourceFormat: Swift.String = Swift.String()

  /// Enables the installation of ConfigSync.
  /// If set to true, ConfigSync resources will be created and the other
  /// ConfigSync fields will be applied if exist.
  /// If set to false, all other ConfigSync fields will be ignored, ConfigSync
  /// resources will be deleted.
  /// If omitted, ConfigSync resources will be managed depends on the presence
  /// of the git or oci field.
  public var enabled: Swift.Bool? = nil

  /// Set to true to enable the Config Sync admission webhook to prevent drifts.
  /// If set to `false`, disables the Config Sync admission webhook and does not
  /// prevent drifts.
  public var preventDrift: Swift.Bool = Swift.Bool()

  /// OCI repo configuration for the cluster
  public var oci: OciConfig? = nil

  /// The Email of the Google Cloud Service Account (GSA) used for exporting
  /// Config Sync metrics to Cloud Monitoring when Workload Identity is enabled.
  /// The GSA should have the Monitoring Metric Writer
  /// (roles/monitoring.metricWriter) IAM role.
  /// The Kubernetes ServiceAccount `default` in the namespace
  /// `config-management-monitoring` should be bound to the GSA.
  public var metricsGcpServiceAccountEmail: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ConfigSync`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ConfigSync().with { $0.git = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let git = CodingKeys(stringValue: "git")
    static let sourceFormat = CodingKeys(stringValue: "sourceFormat")
    static let enabled = CodingKeys(stringValue: "enabled")
    static let preventDrift = CodingKeys(stringValue: "preventDrift")
    static let oci = CodingKeys(stringValue: "oci")
    static let metricsGcpServiceAccountEmail = CodingKeys(
      stringValue: "metricsGcpServiceAccountEmail")

    static let _knownKeys: Set<Swift.String> = [
      "git",
      "sourceFormat",
      "enabled",
      "preventDrift",
      "oci",
      "metricsGcpServiceAccountEmail",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.git = try container.decodeIfPresent(GitConfig.self, forKey: .git)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .sourceFormat) {
      self.sourceFormat = value
    }
    self.enabled = try container.decodeIfPresent(Swift.Bool.self, forKey: .enabled)
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .preventDrift) {
      self.preventDrift = value
    }
    self.oci = try container.decodeIfPresent(OciConfig.self, forKey: .oci)
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .metricsGcpServiceAccountEmail)
    {
      self.metricsGcpServiceAccountEmail = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.git, forKey: .git)
    try container.encode(self.sourceFormat, forKey: .sourceFormat)
    try container.encodeIfPresent(self.enabled, forKey: .enabled)
    try container.encode(self.preventDrift, forKey: .preventDrift)
    try container.encodeIfPresent(self.oci, forKey: .oci)
    try container.encode(self.metricsGcpServiceAccountEmail, forKey: .metricsGcpServiceAccountEmail)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkehub.configmanagement.v1.ConfigSync"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
