// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// The state of ConfigSync's deployment on a cluster
public struct ConfigSyncDeploymentState: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Deployment state of the importer pod
  public var importer: DeploymentState = DeploymentState()

  /// Deployment state of the syncer pod
  public var syncer: DeploymentState = DeploymentState()

  /// Deployment state of the git-sync pod
  public var gitSync: DeploymentState = DeploymentState()

  /// Deployment state of the monitor pod
  public var monitor: DeploymentState = DeploymentState()

  /// Deployment state of reconciler-manager pod
  public var reconcilerManager: DeploymentState = DeploymentState()

  /// Deployment state of root-reconciler
  public var rootReconciler: DeploymentState = DeploymentState()

  /// Deployment state of admission-webhook
  public var admissionWebhook: DeploymentState = DeploymentState()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ConfigSyncDeploymentState`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ConfigSyncDeploymentState().with { $0.importer = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let importer = CodingKeys(stringValue: "importer")
    static let syncer = CodingKeys(stringValue: "syncer")
    static let gitSync = CodingKeys(stringValue: "gitSync")
    static let monitor = CodingKeys(stringValue: "monitor")
    static let reconcilerManager = CodingKeys(stringValue: "reconcilerManager")
    static let rootReconciler = CodingKeys(stringValue: "rootReconciler")
    static let admissionWebhook = CodingKeys(stringValue: "admissionWebhook")

    static let _knownKeys: Set<Swift.String> = [
      "importer",
      "syncer",
      "gitSync",
      "monitor",
      "reconcilerManager",
      "rootReconciler",
      "admissionWebhook",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(DeploymentState.self, forKey: .importer) {
      self.importer = value
    }
    if let value = try container.decodeIfPresent(DeploymentState.self, forKey: .syncer) {
      self.syncer = value
    }
    if let value = try container.decodeIfPresent(DeploymentState.self, forKey: .gitSync) {
      self.gitSync = value
    }
    if let value = try container.decodeIfPresent(DeploymentState.self, forKey: .monitor) {
      self.monitor = value
    }
    if let value = try container.decodeIfPresent(DeploymentState.self, forKey: .reconcilerManager) {
      self.reconcilerManager = value
    }
    if let value = try container.decodeIfPresent(DeploymentState.self, forKey: .rootReconciler) {
      self.rootReconciler = value
    }
    if let value = try container.decodeIfPresent(DeploymentState.self, forKey: .admissionWebhook) {
      self.admissionWebhook = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.importer, forKey: .importer)
    try container.encode(self.syncer, forKey: .syncer)
    try container.encode(self.gitSync, forKey: .gitSync)
    try container.encode(self.monitor, forKey: .monitor)
    try container.encode(self.reconcilerManager, forKey: .reconcilerManager)
    try container.encode(self.rootReconciler, forKey: .rootReconciler)
    try container.encode(self.admissionWebhook, forKey: .admissionWebhook)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkehub.configmanagement.v1.ConfigSyncDeploymentState"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
