// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Git repo configuration for a single cluster.
public struct GitConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The URL of the Git repository to use as the source of truth.
  public var syncRepo: Swift.String = Swift.String()

  /// The branch of the repository to sync from. Default: master.
  public var syncBranch: Swift.String = Swift.String()

  /// The path within the Git repository that represents the top level of the
  /// repo to sync. Default: the root directory of the repository.
  public var policyDir: Swift.String = Swift.String()

  /// Period in seconds between consecutive syncs. Default: 15.
  public var syncWaitSecs: Swift.Int64 = Swift.Int64()

  /// Git revision (tag or hash) to check out. Default HEAD.
  public var syncRev: Swift.String = Swift.String()

  /// Type of secret configured for access to the Git repo. Must be one of ssh,
  /// cookiefile, gcenode, token, gcpserviceaccount or none. The
  /// validation of this is case-sensitive. Required.
  public var secretType: Swift.String = Swift.String()

  /// URL for the HTTPS proxy to be used when communicating with the Git repo.
  public var httpsProxy: Swift.String = Swift.String()

  /// The Google Cloud Service Account Email used for auth when secret_type is
  /// gcpServiceAccount.
  public var gcpServiceAccountEmail: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `GitConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GitConfig().with { $0.syncRepo = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let syncRepo = CodingKeys(stringValue: "syncRepo")
    static let syncBranch = CodingKeys(stringValue: "syncBranch")
    static let policyDir = CodingKeys(stringValue: "policyDir")
    static let syncWaitSecs = CodingKeys(stringValue: "syncWaitSecs")
    static let syncRev = CodingKeys(stringValue: "syncRev")
    static let secretType = CodingKeys(stringValue: "secretType")
    static let httpsProxy = CodingKeys(stringValue: "httpsProxy")
    static let gcpServiceAccountEmail = CodingKeys(stringValue: "gcpServiceAccountEmail")

    static let _knownKeys: Set<Swift.String> = [
      "syncRepo",
      "syncBranch",
      "policyDir",
      "syncWaitSecs",
      "syncRev",
      "secretType",
      "httpsProxy",
      "gcpServiceAccountEmail",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .syncRepo) {
      self.syncRepo = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .syncBranch) {
      self.syncBranch = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .policyDir) {
      self.policyDir = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .syncWaitSecs) {
      self.syncWaitSecs = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .syncRev) {
      self.syncRev = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .secretType) {
      self.secretType = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .httpsProxy) {
      self.httpsProxy = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .gcpServiceAccountEmail)
    {
      self.gcpServiceAccountEmail = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.syncRepo, forKey: .syncRepo)
    try container.encode(self.syncBranch, forKey: .syncBranch)
    try container.encode(self.policyDir, forKey: .policyDir)
    try container.encode(self.syncWaitSecs, forKey: .syncWaitSecs)
    try container.encode(self.syncRev, forKey: .syncRev)
    try container.encode(self.secretType, forKey: .secretType)
    try container.encode(self.httpsProxy, forKey: .httpsProxy)
    try container.encode(self.gcpServiceAccountEmail, forKey: .gcpServiceAccountEmail)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkehub.configmanagement.v1.GitConfig"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
