// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// **Anthos Config Management**: State for a single cluster.
public struct MembershipState: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// This field is set to the `cluster_name` field of the Membership Spec if it
  /// is not empty. Otherwise, it is set to the cluster's fleet membership name.
  public var clusterName: Swift.String = Swift.String()

  /// Membership configuration in the cluster. This represents the actual state
  /// in the cluster, while the MembershipSpec in the FeatureSpec represents
  /// the intended state
  public var membershipSpec: MembershipSpec? = nil

  /// Current install status of ACM's Operator
  public var operatorState: OperatorState? = nil

  /// Current sync status
  public var configSyncState: ConfigSyncState? = nil

  /// PolicyController status
  public var policyControllerState: PolicyControllerState? = nil

  /// Hierarchy Controller status
  public var hierarchyControllerState: HierarchyControllerState? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `MembershipState`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = MembershipState().with { $0.clusterName = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let clusterName = CodingKeys(stringValue: "clusterName")
    static let membershipSpec = CodingKeys(stringValue: "membershipSpec")
    static let operatorState = CodingKeys(stringValue: "operatorState")
    static let configSyncState = CodingKeys(stringValue: "configSyncState")
    static let policyControllerState = CodingKeys(stringValue: "policyControllerState")
    static let hierarchyControllerState = CodingKeys(stringValue: "hierarchyControllerState")

    static let _knownKeys: Set<Swift.String> = [
      "clusterName",
      "membershipSpec",
      "operatorState",
      "configSyncState",
      "policyControllerState",
      "hierarchyControllerState",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .clusterName) {
      self.clusterName = value
    }
    self.membershipSpec = try container.decodeIfPresent(
      MembershipSpec.self, forKey: .membershipSpec)
    self.operatorState = try container.decodeIfPresent(OperatorState.self, forKey: .operatorState)
    self.configSyncState = try container.decodeIfPresent(
      ConfigSyncState.self, forKey: .configSyncState)
    self.policyControllerState = try container.decodeIfPresent(
      PolicyControllerState.self, forKey: .policyControllerState)
    self.hierarchyControllerState = try container.decodeIfPresent(
      HierarchyControllerState.self, forKey: .hierarchyControllerState)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.clusterName, forKey: .clusterName)
    try container.encodeIfPresent(self.membershipSpec, forKey: .membershipSpec)
    try container.encodeIfPresent(self.operatorState, forKey: .operatorState)
    try container.encodeIfPresent(self.configSyncState, forKey: .configSyncState)
    try container.encodeIfPresent(self.policyControllerState, forKey: .policyControllerState)
    try container.encodeIfPresent(self.hierarchyControllerState, forKey: .hierarchyControllerState)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkehub.configmanagement.v1.MembershipState"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
