// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// OCI repo configuration for a single cluster
public struct OciConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The OCI image repository URL for the package to sync from.
  /// e.g. `LOCATION-docker.pkg.dev/PROJECT_ID/REPOSITORY_NAME/PACKAGE_NAME`.
  public var syncRepo: Swift.String = Swift.String()

  /// The absolute path of the directory that contains
  /// the local resources.  Default: the root directory of the image.
  public var policyDir: Swift.String = Swift.String()

  /// Period in seconds between consecutive syncs. Default: 15.
  public var syncWaitSecs: Swift.Int64 = Swift.Int64()

  /// Type of secret configured for access to the Git repo.
  public var secretType: Swift.String = Swift.String()

  /// The Google Cloud Service Account Email used for auth when secret_type is
  /// gcpServiceAccount.
  public var gcpServiceAccountEmail: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `OciConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = OciConfig().with { $0.syncRepo = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let syncRepo = CodingKeys(stringValue: "syncRepo")
    static let policyDir = CodingKeys(stringValue: "policyDir")
    static let syncWaitSecs = CodingKeys(stringValue: "syncWaitSecs")
    static let secretType = CodingKeys(stringValue: "secretType")
    static let gcpServiceAccountEmail = CodingKeys(stringValue: "gcpServiceAccountEmail")

    static let _knownKeys: Set<Swift.String> = [
      "syncRepo",
      "policyDir",
      "syncWaitSecs",
      "secretType",
      "gcpServiceAccountEmail",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .syncRepo) {
      self.syncRepo = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .policyDir) {
      self.policyDir = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .syncWaitSecs) {
      self.syncWaitSecs = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .secretType) {
      self.secretType = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .gcpServiceAccountEmail)
    {
      self.gcpServiceAccountEmail = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.syncRepo, forKey: .syncRepo)
    try container.encode(self.policyDir, forKey: .policyDir)
    try container.encode(self.syncWaitSecs, forKey: .syncWaitSecs)
    try container.encode(self.secretType, forKey: .secretType)
    try container.encode(self.gcpServiceAccountEmail, forKey: .gcpServiceAccountEmail)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkehub.configmanagement.v1.OciConfig"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
