// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Configuration for Policy Controller
public struct PolicyController: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Enables the installation of Policy Controller.
  /// If false, the rest of PolicyController fields take no
  /// effect.
  public var enabled: Swift.Bool = Swift.Bool()

  /// Installs the default template library along with Policy Controller.
  public var templateLibraryInstalled: Swift.Bool? = nil

  /// Sets the interval for Policy Controller Audit Scans (in seconds).
  /// When set to 0, this disables audit functionality altogether.
  public var auditIntervalSeconds: Swift.Int64? = nil

  /// The set of namespaces that are excluded from Policy Controller checks.
  /// Namespaces do not need to currently exist on the cluster.
  public var exemptableNamespaces: [Swift.String] = []

  /// Enables the ability to use Constraint Templates that reference to objects
  /// other than the object currently being evaluated.
  public var referentialRulesEnabled: Swift.Bool = Swift.Bool()

  /// Logs all denies and dry run failures.
  public var logDeniesEnabled: Swift.Bool = Swift.Bool()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `PolicyController`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PolicyController().with { $0.enabled = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let enabled = CodingKeys(stringValue: "enabled")
    static let templateLibraryInstalled = CodingKeys(stringValue: "templateLibraryInstalled")
    static let auditIntervalSeconds = CodingKeys(stringValue: "auditIntervalSeconds")
    static let exemptableNamespaces = CodingKeys(stringValue: "exemptableNamespaces")
    static let referentialRulesEnabled = CodingKeys(stringValue: "referentialRulesEnabled")
    static let logDeniesEnabled = CodingKeys(stringValue: "logDeniesEnabled")

    static let _knownKeys: Set<Swift.String> = [
      "enabled",
      "templateLibraryInstalled",
      "auditIntervalSeconds",
      "exemptableNamespaces",
      "referentialRulesEnabled",
      "logDeniesEnabled",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .enabled) {
      self.enabled = value
    }
    self.templateLibraryInstalled = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .templateLibraryInstalled)
    self.auditIntervalSeconds = try container.decodeIfPresent(
      Swift.Int64.self, forKey: .auditIntervalSeconds)
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .exemptableNamespaces)
    {
      self.exemptableNamespaces = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .referentialRulesEnabled)
    {
      self.referentialRulesEnabled = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .logDeniesEnabled) {
      self.logDeniesEnabled = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.enabled, forKey: .enabled)
    try container.encodeIfPresent(self.templateLibraryInstalled, forKey: .templateLibraryInstalled)
    try container.encodeIfPresent(self.auditIntervalSeconds, forKey: .auditIntervalSeconds)
    try container.encode(self.exemptableNamespaces, forKey: .exemptableNamespaces)
    try container.encode(self.referentialRulesEnabled, forKey: .referentialRulesEnabled)
    try container.encode(self.logDeniesEnabled, forKey: .logDeniesEnabled)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkehub.configmanagement.v1.PolicyController"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
